### ISSUE TITLE
com.valvesoftware.Steam.Utility.gamescope is end-of-life

### ISSUE THREAD

**Issue by RayJW** [flathub/com.heroicgameslauncher.hgl#100]
When updating Flatpaks this message gets displayed:

```shell
Info: runtime com.valvesoftware.Steam.Utility.gamescope branch stable is end-of-life, with reason:
    The gamescope Flatpak has been migrated to org.freedesktop.Platform.VulkanLayer.gamescope.
Info: applications using this extension:
    com.heroicgameslauncher.hgl
```

This should probably be a straight forward fix since it was just migrated.

**Comment by flavioislima** [comment]
@RayJW I don't see where we are declaring the extension on the manifest. 
If you remove the old one and install the new one Heroic will work the same because it is installed on the same path.

**Comment by RayJW** [comment]
So, after investigating, it seems like this might be a Flatpak issue. I ran `flatpak uninstall --unused` and this would not get rid of it. However, when manually uninstalling the extension and then running `flatpak update` it does not try to reinstall the extension like it should. So it seems like the warning stays after the migration because, due to the same path being used it doesn't know, that it can uninstall the extension safely now.
I think this issue can be closed then :)

**Comment by flavioislima** [comment]
@RayJW yes, same happened with me.

No problem! :)
