### ISSUE TITLE
Add libFAudio dependency

### ISSUE THREAD

**Issue by aleasto** [flathub/com.heroicgameslauncher.hgl#13]
For whatever reason lutris builds of wine still link against libFAudio

**Comment by flavioislima** [comment]
What do you mean? How can I add that and why it is needed?

**Comment by aleasto** [comment]
Actually the issue is that Heroic Games Launcher does not set LD_LIBRARY_PATH when launching wine so it's trying to access system libraries instead of the bundled ones and libFAudio is missing.

Proton already does this on its own.
This should probably be fixed upstream.

**Comment by aleasto** [comment]
Didn't realize you also maintained upstream.
Anyways i filed an issue there too https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1334
