### ISSUE TITLE
Too small mouse pointer when using fractional scaling in the latest flatpak commits.

### ISSUE THREAD

**Issue by TheRsKing** [flathub/com.heroicgameslauncher.hgl#177]
https://github.com/flathub/com.heroicgameslauncher.hgl/pull/175

**Comment by TheRsKing** [comment]
> What desktop do you use ?

OS: Aeon 6.11.8-1-default (linux)
Desktop: gnome 47
running inside a Flatpak container

Software Versions:
  Heroic: 2.15.2 Emeth
  Legendary: 0.20.36 Urban Flight (Heroic)
  gogdl: 1.1.2
  comet: comet 0.1.2

**Comment by Etaash-mathamsetty** [comment]
this is an issue with gnome you can work around it by setting the XCURSOR_PATH env
