### ISSUE TITLE
duplicate appindicators on gnome 

### ISSUE THREAD

**Issue by jumpers775** [flathub/com.heroicgameslauncher.hgl#20]
![image](https://user-images.githubusercontent.com/78500318/184518459-17c49025-3b10-4b1a-b81d-2d0291588d10.png)

on gnome when using this flatpak and the "AppIndicator and KStatusNotifierItem Support" there are duplicate menubar items. this des not occur when using the non-flatpak variant.

**Comment by flavioislima** [comment]
I wonder if this is an Electron issue. 
Did you checked if this happened before or only on latest release?

**Comment by jumpers775** [comment]
this has happened as far back as have used this app, and on the latest release.

**Comment by flavioislima** [comment]
Answered on original issue: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1722
