### ISSUE TITLE
Heroic doesn't apply default language setting

### ISSUE THREAD

**Issue by 1basti1** [flathub/com.heroicgameslauncher.hgl#45]
I set my language "de" as the default setting.

I downloaded a game, but it was English, I had to manually set it to de (for German) after the game was installed.

Edit: I'm on steam deck with the currently stable steamOS 3.4

**Comment by flavioislima** [comment]
Better to open this issue on the official repo. This one is just for flatpak build issues or improvements, not heroic itself.
